/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types */
        get: operations["AdminRoutes_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all upcoming bookings across all event types. Sorted by startUtc ascending. Optional query parameters from and to filter the date range. */
        get: operations["AdminRoutes_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new event type */
        post: operations["AdminRoutes_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type by ID */
        get: operations["AdminRoutes_getEventType"];
        /** @description Update an existing event type */
        put: operations["AdminRoutes_updateEventType"];
        post?: never;
        /** @description Delete an event type */
        delete: operations["AdminRoutes_deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new booking for a selected slot. The server calculates endUtc = startUtc + EventType.durationMinutes. Before saving, the server checks for overlaps with existing bookings (all event types) in a transaction to prevent race conditions. startUtc must fall within valid working hours and the 14-day booking window. Returns 409 Conflict if the slot is already taken. Returns 400 if startUtc is invalid (outside working hours, outside 14-day window, in the past). Returns 404 if eventTypeId does not exist. */
        post: operations["PublicRoutes_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types available for booking (name, description, durationMinutes) */
        get: operations["PublicRoutes_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get details of a single event type */
        get: operations["PublicRoutes_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get free booking slots for a given event type within the next 14 days. Slots are computed based on the event type duration, owner working hours (server config), and exclude any slots that overlap with existing bookings of any event type. All returned slots have duration equal to EventType.durationMinutes. Slots are sorted by startUtc ascending. If from or to are not provided, defaults to [now, now + 14 days). Returns 400 if from >= to or values are outside the 14-day window. Returns 404 if eventTypeId does not exist. */
        get: operations["PublicRoutes_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "id": "bk-1",
         *       "eventTypeId": "et-1",
         *       "eventTypeName": "Consultation",
         *       "startUtc": "2025-06-01T09:00:00Z",
         *       "endUtc": "2025-06-01T09:30:00Z",
         *       "guestName": "Alice Johnson",
         *       "guestEmail": "alice@example.com",
         *       "createdAtUtc": "2025-05-20T08:00:00Z"
         *     }
         */
        Booking: {
            readonly id: string;
            eventTypeId: string;
            eventTypeName: string;
            /**
             * Format: date-time
             * @description Start of the booking in UTC
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description End of the booking in UTC, calculated as startUtc + EventType.durationMinutes
             */
            endUtc: string;
            guestName: string;
            /** @description Guest email address */
            guestEmail: string;
            notes?: string;
            /**
             * Format: date-time
             * @description Creation timestamp in UTC
             */
            readonly createdAtUtc: string;
        };
        BookingCreate: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Start of the booking in UTC. Must fall within a valid free slot.
             */
            startUtc: string;
            guestName: string;
            /** @description Guest email address */
            guestEmail: string;
            notes?: string;
        };
        /**
         * @example {
         *       "id": "et-1",
         *       "name": "Consultation",
         *       "durationMinutes": 30
         *     }
         */
        EventType: {
            readonly id: string;
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        EventTypeCreate: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        EventTypeUpdate: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        Owner: {
            readonly id: string;
            name: string;
            timeZone: string;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        /**
         * @example {
         *       "startUtc": "2025-06-01T09:00:00Z",
         *       "endUtc": "2025-06-01T09:30:00Z",
         *       "eventTypeId": "et-1"
         *     }
         */
        Slot: {
            /**
             * Format: date-time
             * @description Start of the slot in UTC
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description End of the slot in UTC, calculated as startUtc + EventType.durationMinutes
             */
            endUtc: string;
            eventTypeId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminRoutes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "et-1",
                     *         "name": "Consultation",
                     *         "durationMinutes": 30
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    AdminRoutes_listBookings: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "bk-1",
                     *         "eventTypeId": "et-1",
                     *         "eventTypeName": "Consultation",
                     *         "startUtc": "2025-06-01T09:00:00Z",
                     *         "endUtc": "2025-06-01T09:30:00Z",
                     *         "guestName": "Alice Johnson",
                     *         "guestEmail": "alice@example.com",
                     *         "createdAtUtc": "2025-05-20T08:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    AdminRoutes_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Consultation",
                 *       "durationMinutes": 30
                 *     }
                 */
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "et-1",
                     *       "name": "Consultation",
                     *       "durationMinutes": 30
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminRoutes_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "et-1",
                     *       "name": "Consultation",
                     *       "durationMinutes": 30
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminRoutes_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Consultation",
                 *       "durationMinutes": 60
                 *     }
                 */
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "et-1",
                     *       "name": "Consultation",
                     *       "durationMinutes": 60
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminRoutes_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PublicRoutes_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "eventTypeId": "et-1",
                 *       "startUtc": "2025-06-01T09:00:00Z",
                 *       "guestName": "Alice Johnson",
                 *       "guestEmail": "alice@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "bk-1",
                     *       "eventTypeId": "et-1",
                     *       "eventTypeName": "Consultation",
                     *       "startUtc": "2025-06-01T09:00:00Z",
                     *       "endUtc": "2025-06-01T09:30:00Z",
                     *       "guestName": "Alice Johnson",
                     *       "guestEmail": "alice@example.com",
                     *       "createdAtUtc": "2025-05-20T08:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PublicRoutes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "et-1",
                     *         "name": "Consultation",
                     *         "durationMinutes": 30
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    PublicRoutes_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PublicRoutes_getSlots: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "startUtc": "2025-06-01T09:00:00Z",
                     *         "endUtc": "2025-06-01T09:30:00Z",
                     *         "eventTypeId": "et-1"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
